name: Metrics embed

on:
  # Schedule the workflow to run daily at midnight UTC
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Classic template configuration
          filename: metrics.classic.svg
          template: classic
          base: header, repositories
          
          # Languages plugin
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_other: no
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          
          # Lines plugin (works well with classic template)
          plugin_lines: yes
